.PHONY: clean All

All:
	@echo "----------Building project:[ Swyft - Debug ]----------"
	@cd "Swyft" && "$(MAKE)" -f  "Swyft.mk"
clean:
	@echo "----------Cleaning project:[ Swyft - Debug ]----------"
	@cd "Swyft" && "$(MAKE)" -f  "Swyft.mk" clean
